// Generated by auto imports
export {}
declare global {
  const createError: typeof import('../../node_modules/nuxt/dist/app/composables/error').createError
  const defineAppConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const getRouteRules: typeof import('../../node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const setResponseStatus: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const useAppConfig: typeof import('../../node_modules/nuxt/dist/app/config').useAppConfig
  const useRuntimeConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
}