import type { Config } from "tailwindcss";

export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  safelist: ["bg-gradient-to-tr", "from-brand-orange", "to-brand-orange-light"],
  theme: {
    screens: {
      xs: { min: "360px" },
      sm: { min: "375px" },
      "sm-plus": { min: "384px" },
      "phone-sm": { min: "411px" },
      "phone-md": { min: "412px" },
      "phone-lg": { min: "414px" },
      "tablet-xs": { min: "601px" },
      "tablet-sm": { min: "768px" },
      "tablet-md": { min: "800px" },
      "tablet-lg": { min: "962px" },
      lg: { min: "1024px" },
      "laptop-sm": { min: "1152px" },
      xl: { min: "1280px" },
      laptop: { min: "1366px" },
      desktop: { min: "1440px" },
      "desktop-lg": { min: "1500px" },
      "2xl": { min: "1536px" },
      "3xl": { min: "1920px" },
    },
    extend: {
      colors: {
        "brand-orange": "#FD5531",
        "brand-orange-light": "#FE673B",
        "background-light": "#F4F6FB",
        "background-light-alt": "#EBF1FF",
        "white-soft": "#FAFAFA",
        "black-primary": "#0F1221",
        "black-opacity-50": "rgba(15, 18, 33, 0.5)",
        "black-opacity-10": "rgba(15, 18, 33, 0.1)",
        "gray-dark": "#3F4551",
        gray: "#858A93",
        "gray-light": "#CBCCCF",
        "orange-pastel": "#FAD0C7",
        "travu-dark-1": "#111827",
        "travu-dark-2": "#171E2D",
        weatherly: "#061f18",
        vect: "#16131D",
        "success-green": "#00BF69",
        ear1: "#00070F",
        getfood: "#064442",
        talkease: "#6C47FF",
        tripvoyager: "#3E64FF",
        "purple-light": "#F3F5FF",
        "sky-light": "#ECF0F3",
        "macos-dark": "#1E1F2B",
        "oneui-dark": "#20222C",
        "purple-primary": "#546DEE",
      },
      fontFamily: {
        heading: ["Grifter"],
        body: ["Plus Jakarta Sans"],
      },
      fontSize: {
        "heading-1": "2.125rem",
        "heading-2": "2.5rem",
        "heading-3": "2.625rem",
        "heading-4": "2.8rem",
        "heading-5": "3.25rem",
        "heading-6": "3.375rem",
        display: "1.75rem",
      },
      lineHeight: {
        tight: "2.75rem",
        normal: "3.25rem",
        loose: "3.5rem",
        "extra-loose": "4rem",
      },
      width: {
        "width-1": "1.0625rem",
        "width-2": "1.125rem",
        "width-3": "1.5625rem",
        "width-4": "1.6875rem",
        "width-5": "1.875rem",
        "width-6": "2.813rem",
        "width-7": "3.125rem",
        "width-8": "3.75rem",
        "width-9": "4.5rem",
        "width-10": "5.5rem",
        "width-11": "6.5rem",
        "width-12": "7.5rem",
        "width-13": "8.5rem",
        "width-14": "9.5rem",
        "width-15": "10.5rem",
        "width-16": "10.938rem",
        "width-17": "11.5rem",
        "width-18": "12.979rem",
        "width-19": "16.727rem",
        "width-20": "17.474rem",
      },
      padding: {
        "logo-padding": "4.125rem",
        "padding-width-1": "17rem",
        "padding-width-2": "25rem",
        "padding-width-3": "32rem",
        "spacing-1": "5.5rem",
        "spacing-2": "6.5rem",
      },
      gridRow: {
        "span-7": "span 7 / span 7",
        "span-8": "span 8 / span 8",
        "span-9": "span 9 / span 9",
        "span-10": "span 10 / span 10",
        "span-11": "span 11 / span 11",
        "span-12": "span 12 / span 12",
        "span-13": "span 13 / span 13",
        "span-14": "span 14 / span 14",
        "span-15": "span 15 / span 15",
        "span-16": "span 16 / span 16",
        "span-17": "span 17 / span 17",
        "span-18": "span 18 / span 18",
        "span-19": "span 19 / span 19",
        "span-20": "span 20 / span 20",
      },
      gridAutoRows: {
        "min-0.5": "minmax(0.5rem, auto)",
        "min-1": "minmax(1rem, auto)",
        "min-1.25": "minmax(1.25rem, auto)",
        "min-1.5": "minmax(1.5rem, auto)",
        "min-2": "minmax(2rem, auto)",
        "min-3": "minmax(3rem, auto)",
        "min-4": "minmax(4rem, auto)",
        "min-5": "minmax(5rem, auto)",
        "min-6": "minmax(6rem, auto)",
        "min-md": "minmax(20rem, auto)",
        "min-lg": "minmax(24rem, auto)",
        "min-xl": "minmax(32rem, auto)",
        "min-2xl": "minmax(36rem, auto)",
        "min-3xl": "minmax(40rem, auto)",
      },
    },
  },
  plugins: [],
} satisfies Config;
