// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/23/2026, 5:54:30 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/adegb/Tech/Projects/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adegb/Tech/Projects/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adegb/Tech/Projects/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adegb/Tech/Projects/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adegb/Tech/Projects/portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/adegb/Tech/Projects/portfolio/composables/**/*.{js,ts,mjs}","C:/Users/adegb/Tech/Projects/portfolio/utils/**/*.{js,ts,mjs}","C:/Users/adegb/Tech/Projects/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adegb/Tech/Projects/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adegb/Tech/Projects/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/adegb/Tech/Projects/portfolio/app.config.{js,ts,mjs}"]}},
{},
(() => {const cfg=configMerger(undefined, cfg2);cfg.content = cfg.purge;;return cfg;})()
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;